CREATE TABLE customers
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                             NOT NULL,
    last_name  VARCHAR(255)                             NOT NULL,
    phone      VARCHAR(255)                             NOT NULL,
    password   VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE orders
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version             INTEGER                                  NOT NULL,
    customer_first_name VARCHAR(255)                             NOT NULL,
    customer_last_name  VARCHAR(255)                             NOT NULL,
    customer_phone      VARCHAR(255)                             NOT NULL,
    delivery_address    VARCHAR(255)                             NOT NULL,
    pilotes             INTEGER                                  NOT NULL,
    total_price         INTEGER                                  NOT NULL,
    created_at          timestamptz                              NOT NULL,
    updated_at          timestamptz                              NOT NULL,
    CONSTRAINT pk_orders PRIMARY KEY (id)
);

ALTER TABLE customers
    ADD CONSTRAINT uc_customers_phone UNIQUE (phone);